
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucketopop1:
    Type: AWS::S3::Bucket
Outputs:
  BucketName:
    Value: !Ref 'S3Bucketopop1'
    Description: Name of the sample Amazon S3 bucket with a logging configuration.
          
